- name: remove timer
  file:
    path: /etc/systemd/system/zhdk-sync.timer
    state: absent

- name: remove service 
  file:
    path: /etc/systemd/system/zhdk-sync.service
    state: absent

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl

- name: remove deploy target dir(s)
  file:
    path: "{{madek_zhdk_sync_root_dir}}"
    state: absent

- name: remove madek-sync user
  user:
    name: '{{madek_zhdk_sync_user}}'
    state: absent
    force: yes

- name: remove madek-sync group
  group:
    name: '{{madek_zhdk_sync_user}}'
    state: absent
