jobs:
  uberjar:
    name: Build uberjar
    run_when:
      on any branch:
        type: branch
        include_match: ^.*$
    context:
      tasks:
        build:
          traits:
            'JDK 8': true
            'Leiningen': true
          scripts:
            uberjar:
              body: |
                set -euxo
                lein uberjar
